-- 코드를 입력하세요
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM((C.SALES * A.PRICE)) AS TOTAL_SALES
FROM BOOK A
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE, '%Y%m') = '202201'
GROUP BY A.CATEGORY, B.AUTHOR_ID
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC